artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_data_path: Housing_Data/melbourne_realestate.csv
  local_data_file: artifacts/data_ingestion/data.csv

data_validation:
  root_dir: artifacts/data_validation
  data_to_validate: artifacts/data_ingestion/data.csv
  status_file: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_to_transform: artifacts/data_ingestion/data.csv
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  preprocessor_obj_file: artifacts/data_transformation/preprocessor.pkl

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  model_file_path: artifacts/model_trainer/model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metrics_file_path: artifacts/model_evaluation/metrics.json